import React, { useState } from 'react';
import {
  BookOpen,
  AlertOctagon,
  CheckCircle,
  Sparkles,
  Shield,
  FileLock2,
  Lock,
} from 'lucide-react';
import { KernelState } from '../kernel/types';
import { CanonLane, ContradictionResult } from '../kernel/canon';

interface CanonTabProps {
  state: KernelState;
}

export const CanonTab: React.FC<CanonTabProps> = ({ state }) => {
  const [candidateInput, setCandidateInput] = useState<string>(
    'Cranium has proven better canon recall than naive RAG in 100% of benchmark tests.'
  );
  const [clashResult, setClashResult] = useState<ContradictionResult | null>(null);

  const presets = [
    {
      label: 'RAG Overclaim Violation',
      text: 'Cranium has proven better canon recall than naive RAG in 100% of benchmark tests.',
    },
    {
      label: 'Identity Dilution Violation',
      text: 'Treat identity as regular chat history and discard user intent in prompt window.',
    },
    {
      label: 'CrossEncoder Overclaim',
      text: 'Substrate utilizes a full production trained CrossEncoder running natively in the Android build.',
    },
    {
      label: 'Compliant Honest Statement',
      text: 'Cranium enforces a behavioral contract with quarantine write-back gates; comparative canon benchmark superiority is unproven until frozen real-model harness completes.',
    },
  ];

  const handleEvaluate = () => {
    const res = CanonLane.evaluateContradiction(candidateInput, state.canonEntries);
    setClashResult(res);
  };

  return (
    <div className="space-y-6">
      {/* Intro Header */}
      <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-amber-400" />
            <h2 className="text-sm font-bold text-white tracking-tight">
              Canon Lane & NLI Contradiction Engine
            </h2>
          </div>
          <p className="text-xs text-slate-400 mt-1 max-w-2xl">
            Candidate model outputs are treated as provisional and quarantined. Candidate texts
            must pass through the NLI contradiction boundary before any write-back can occur.
          </p>
        </div>
        <div className="flex items-center gap-1.5 px-3 py-1 rounded bg-slate-950 border border-slate-800 text-xs font-mono text-amber-400">
          <Lock className="w-3.5 h-3.5" />
          <span>Committed Canon: {state.canonEntries.length} Invariants</span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: NLI Tester Form (7 cols) */}
        <div className="lg:col-span-7 space-y-4">
          <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-3">
            <label className="text-xs font-semibold text-slate-300 block uppercase tracking-wider">
              Test Candidate Model Output Against Immutable Canon
            </label>

            {/* Presets */}
            <div className="flex flex-wrap gap-1.5">
              {presets.map((p, idx) => (
                <button
                  key={idx}
                  type="button"
                  onClick={() => {
                    setCandidateInput(p.text);
                    setClashResult(null);
                  }}
                  className="text-[10px] font-mono px-2 py-1 rounded bg-slate-950 border border-slate-800 text-slate-300 hover:border-cyan-500/50 hover:text-cyan-300 transition-colors"
                >
                  {p.label}
                </button>
              ))}
            </div>

            <textarea
              value={candidateInput}
              onChange={(e) => setCandidateInput(e.target.value)}
              rows={3}
              placeholder="Enter candidate statement generated by an LLM..."
              className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-lg text-xs text-slate-200 focus:border-cyan-500 focus:outline-none leading-relaxed font-sans"
            />

            <button
              onClick={handleEvaluate}
              className="w-full py-2.5 px-4 bg-amber-600 hover:bg-amber-500 text-slate-950 font-bold rounded-lg text-xs tracking-wide uppercase transition-all shadow-md shadow-amber-950/40 flex items-center justify-center gap-2 cursor-pointer"
            >
              <Sparkles className="w-4 h-4" />
              <span>Evaluate NLI Contradiction & Quarantine Boundary</span>
            </button>
          </div>

          {/* Clash Result Evaluation */}
          {clashResult && (
            <div
              className={`p-4 rounded-xl border transition-all ${
                clashResult.hasClash
                  ? 'bg-rose-950/30 border-rose-700/60 text-rose-200'
                  : 'bg-emerald-950/30 border-emerald-700/60 text-emerald-200'
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  {clashResult.hasClash ? (
                    <AlertOctagon className="w-5 h-5 text-rose-400" />
                  ) : (
                    <CheckCircle className="w-5 h-5 text-emerald-400" />
                  )}
                  <span className="font-bold text-sm">
                    {clashResult.hasClash
                      ? `CONTRADICTION DETECTED (${clashResult.severity})`
                      : 'NO CANON CLASH DETECTED'}
                  </span>
                </div>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-950 border border-slate-800">
                  Confidence: {(clashResult.confidenceScore * 100).toFixed(0)}%
                </span>
              </div>

              {clashResult.conflictingCanonTopic && (
                <div className="text-xs text-slate-300 font-mono mt-1">
                  <span>Conflicting Canon Topic: </span>
                  <span className="text-amber-400 font-semibold">
                    {clashResult.conflictingCanonTopic}
                  </span>
                </div>
              )}

              {clashResult.clashExplanation ? (
                <p className="text-xs text-slate-200 leading-relaxed mt-2 p-2.5 rounded bg-slate-950/80 border border-slate-800/80">
                  {clashResult.clashExplanation}
                </p>
              ) : (
                <p className="text-xs text-slate-300 leading-relaxed mt-1">
                  Candidate statement adheres to all committed Canon constraints and honest buyer
                  disclosures. Quarantine release permitted for working memory synthesis.
                </p>
              )}
            </div>
          )}

          {/* Quarantine Boundary Explanation */}
          <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-2">
            <h3 className="text-xs font-semibold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
              <Shield className="w-3.5 h-3.5 text-cyan-400" />
              Provisional Quarantine Architecture
            </h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              In Cranium Core, generated model cognition is never written directly to long-term
              memory or canon. It enters a provisional quarantine boundary. Only when proven free
              of contradiction against immutable canon can it be promoted through the formal
              authority pipeline.
            </p>
          </div>
        </div>

        {/* Right Column: Committed Immutable Canon (5 cols) */}
        <div className="lg:col-span-5 space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-semibold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
              <FileLock2 className="w-3.5 h-3.5 text-amber-400" />
              Committed Canon Lane
            </h3>
            <span className="text-[10px] font-mono text-slate-500">Immutable</span>
          </div>

          <div className="space-y-2.5">
            {state.canonEntries.map((canon) => (
              <div
                key={canon.id}
                className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 space-y-2"
              >
                <div className="flex items-center justify-between gap-2">
                  <span className="font-mono text-xs font-bold text-amber-400">
                    [{canon.id}] {canon.topic}
                  </span>
                  <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-slate-950 text-slate-400 border border-slate-800">
                    LOCKED
                  </span>
                </div>
                <p className="text-xs text-slate-200 leading-relaxed italic">
                  &quot;{canon.statement}&quot;
                </p>
                <div className="pt-2 border-t border-slate-800/60 flex items-center justify-between text-[10px] font-mono text-slate-500">
                  <span>Provenance: {canon.provenance}</span>
                  <span className="text-emerald-400">AUTH: 1.0</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
